### ISSUE TITLE
sig-list.md broken links

### ISSUE THREAD

**Issue by flickerfly** [operator-framework/community#10]
The following links do not exist. They are all at the top of https://github.com/operator-framework/community/blob/master/sig-list.md :
- https://github.com/operator-framework/community/blob/master/communication/README.md#weekly-meeting
- https://github.com/operator-framework/community/blob/master/governance.md
- https://github.com/operator-framework/community/blob/master/sig-wg-lifecycle.md

**Comment by asmacdo** [comment]
We dont use this file anymore
