### ISSUE TITLE
REQUEST: New membership for jmccormick2001

### ISSUE THREAD

**Issue by jmccormick2001** [operator-framework/community#27]
### GitHub Username
jmccormick2001

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @dmueller2001 
- @dmesser 

### List of contributions to the Operator Framework org
- PRs reviewed / authored
- Issues responded to
- Subprojects I am involved with include SDK, OLM, operator-registry

**Comment by jmrodri** [comment]
@jmccormick2001 if you are still interested in pursuing this please re-open.
