### ISSUE TITLE
Query Memory usage by operator SDK

### ISSUE THREAD

**Issue by prary** [operator-framework/community#39]
Kiali-operator uses operator sdk and looks like operator sdk generate logs in runner volume which is EmptyDir which uses host resource. 

Any idea how much size it can consume on node, any thoughts on memory usage of this folder would be great?

https://github.com/kiali/kiali/discussions/4374

**Comment by jmrodri** [comment]
Closing this issue in favor of the new issue on the operator sdk repo: https://github.com/operator-framework/operator-sdk/issues/6131
