### ISSUE TITLE
REQUEST: New membership for SimonBaeumer

### ISSUE THREAD

**Issue by SimonBaeumer** [operator-framework/community#56]
### GitHub Username
@SimonBaeumer 

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @joelanford 
- @varshaprasad96 

### List of contributions to the Operator Framework org

**PRs reviewed / authored**
 - https://github.com/operator-framework/helm-operator-plugins/pull/92
 - https://github.com/operator-framework/helm-operator-plugins/pull/107
 - https://github.com/operator-framework/helm-operator-plugins/pull/118

**~~Issues responded to~~**

**Subprojects I am involved with**
 - [helm-operator-plugins ](https://github.com/operator-framework/helm-operator-plugins)
    Currently in the progress of upstreaming our [fork](https://github.com/stackrox/helm-operator), actively contributing and participating in the community meetings.

**Comment by varshaprasad96** [comment]
+1 :)
/lgtm

**Comment by SimonBaeumer** [comment]
Thanks all!
