### ISSUE TITLE
REQUEST: New membership for porridge

### ISSUE THREAD

**Issue by porridge** [operator-framework/community#57]
### GitHub Username
@porridge

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application. Well, @SimonBaeumer asked about us both to keep the noise down :-)

### Sponsors
- @joelanford 
- @varshaprasad96 

#### PRs reviewed / authored

- https://github.com/operator-framework/helm-operator-plugins/pull/114
- https://github.com/operator-framework/operator-sdk/pull/5078
- https://github.com/operator-framework/helm-operator-plugins/pull/112

Some minor docs fixes:

- https://github.com/operator-framework/operator-sdk/pull/5408
- https://github.com/operator-framework/helm-operator-plugins/pull/111
- https://github.com/operator-framework/operator-sdk/pull/4752
- https://github.com/operator-framework/olm-book/pull/47
- https://github.com/operator-framework/operator-sdk/pull/5074

#### Issues responded to

- https://github.com/operator-framework/operator-sdk/issues/5073
- https://github.com/operator-framework/helm-operator-plugins/issues/137

#### Subprojects I am involved with
- https://github.com/operator-framework/helm-operator-plugins
  Currently in the progress of upstreaming our [fork](https://github.com/stackrox/helm-operator), actively contributing and participating in the community meetings.
- https://github.com/operator-framework/operator-sdk
  Drive-by documentation fixes :-)

**Comment by joelanford** [comment]
Invite sent!
