### ISSUE TITLE
REQUEST: New membership for akihikokuroda

### ISSUE THREAD

**Issue by akihikokuroda** [operator-framework/community#58]
### GitHub Username
@akihikokuroda

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @timflannagan
- @awgreene

### List of contributions to the Operator Framework org
- PRs reviewed / authored
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2444
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2448
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2508
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2547
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2510
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2517
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2521
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2530
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2532
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2541
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2545
- https://github.com/operator-framework/operator-lifecycle-manager/pull/2561
- Issues responded to
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2440
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2439
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2507
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2509
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2516
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2522
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2529
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2540
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2544
- https://github.com/operator-framework/operator-lifecycle-manager/issues/2560
- Subprojects I am involved with
- https://github.com/operator-framework/operator-lifecycle-manager
- https://github.com/operator-framework/operator-registry
- https://github.com/operator-framework/api

**Comment by timflannagan** [comment]
+1

**Comment by awgreene** [comment]
+1

**Comment by joelanford** [comment]
Invitation sent. Welcome to Operator Framework @akihikokuroda!
