### ISSUE TITLE
Proposal to amend the charter to improve the specifications for the election of chairs

### ISSUE THREAD

**Issue by joelanford** [operator-framework/community#65]
We conducted an election for operator framework chairs and were forced to make judgements about how exactly to conduct it due to ambiguity in the charter.  In this issue, let's discuss how to amend the charter so that the next election can be run more smoothly.

**Comment by asmacdo** [comment]
The biggest problem IMO was that "who gets to vote" was unclear

**Comment by asmacdo** [comment]
We've just updated our governance model! Hopefully that addresses any concerns :)
