### ISSUE TITLE
Kubecon NA 2022 Maintainer Track session

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/community#67]
Submissions are open for maintainer track sessions for Kubecon NA [here](https://www.surveymonkey.com/r/TB6VW7X).

I think we should submit something, who would be interested in giving the talk? Discuss ITT.

**Comment by jberkhahn** [comment]
I'd be down to go again, and know for sure I would get funding to go if the talk is accepted.

**Comment by asmacdo** [comment]
I'd be interested as well, but I'll happily step aside for someone who hasn't done it before.

**Comment by asmacdo** [comment]
It is done :)
