### ISSUE TITLE
Java Operator SDK wants to join Operator Framework

### ISSUE THREAD

**Issue by jberkhahn** [operator-framework/community#90]
[Java Operator SDK](https://github.com/java-operator-sdk/java-operator-sdk) wants to join OF. This is a meta issue concerning their request. 

For reference, this is the checklist for joining:

- [x] Have a mission that aligns with the Operator Framework goals
- [x] Are appropriately licensed
- [x] Governance structure is fully documented in a GOVERNANCE file
- [x] Governance rules are modifiable by project leaders through a defined process.
- [x] Embrace the Operator Framework and CNCF values
- [x] Are under active development
- [x] Consist of high quality code and designs
- [x] Have at least 3 Approvers (Experimental Subprojects must have at least 1)

**Comment by jmrodri** [comment]
- [] fofof

**Comment by jberkhahn** [comment]
[Their license is apache 2.0, so that looks good](https://github.com/java-operator-sdk/java-operator-sdk/blob/main/LICENSE)

**Comment by csviri** [comment]
Hi All, first thank you for being open to this.

The 3 approvevers are:
@metacosm
@csviri
@andreaTP

**Comment by csviri** [comment]
Shall we have a separate Governance and Mission Statement document? 
Or we can say that we are fine with the shared in this repo. (I guess that holds for all project by default)

**Comment by asmacdo** [comment]
Yes, we wrote the governance in such a way that it applies to all projects by default. You can. supplement if you want to (especially if you have values or a mission you want to explicitly call out).

We did it this way mostly to accommodate projects that might already have a governance doc they want to keep. If you don't have strong feelings, it's recommended to stick with the default :)

**Comment by asmacdo** [comment]
Also, you can. go with the default now and make governance changes later with review from the steering committee

**Comment by csviri** [comment]
So is there anything else missing? :)

**Comment by jmrodri** [comment]
>  Consist of high quality code and designs

**Comment by asmacdo** [comment]
I've checked the boxes for governance, values, and mission. All of them will be in place by default. 

If you decide to add any governance now, we'll need to review it before the vote. If you add governance later, please see the top level governance doc for the process to add and approve.

**Comment by jmrodri** [comment]
> > Consist of high quality code and designs
> 
> was that a dig to our code quality, @jmrodri? wink

@metacosm no, it was an unfinished message. I updated it now. Sorry about the confusion.

**Comment by metacosm** [comment]
I approve of that move.

**Comment by csviri** [comment]
I approve

**Comment by andreaTP** [comment]
I approve the move

**Comment by jberkhahn** [comment]
I approve this move as a steering committee member of Operator Framework.

**Comment by asmacdo** [comment]
I approve this move as a steering committee member of Operator Framework.

**Comment by joelanford** [comment]
I'm also a +1 on accepting Java Operator SDK into the Operator Framework!

**Comment by tlwu2013** [comment]
+1 on having [java-operator-sdk](https://github.com/java-operator-sdk/java-operator-sdk) as a part of the Operator Framework family!

**Comment by awgreene** [comment]
Big +1 on having the java-operator-sdk join the framework!

**Comment by varshaprasad96** [comment]
+1 for [java-operator-SDK](https://github.com/java-operator-sdk/java-operator-sdk) joining Operator Framework community!

**Comment by grokspawn** [comment]
+1 for java-operator-SDK joining OF

**Comment by oceanc80** [comment]
+1 for java-operator-SDK joining OF

**Comment by everettraven** [comment]
+1 to java-operator-sdk joining Operator Framework

**Comment by gallettilance** [comment]
+1

**Comment by joelanford** [comment]
It seems we neglected to close this issue out once the approval was finalized!

Officially, the Java Operator SDK subproject was approved by the OF steering committee as of April 4, 2023.
