### ISSUE TITLE
REQUEST: New membership for OchiengEd

### ISSUE THREAD

**Issue by OchiengEd** [operator-framework/community#93]
### GitHub Username
@OchiengEd

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @varshaprasad96
- @jberkhahn

### List of contributions to the Operator Framework org
- PRs reviewed / authored
- Issues responded to
 [#6369](https://github.com/operator-framework/operator-sdk/issues/6369)
 [#6353](https://github.com/operator-framework/operator-sdk/issues/6353)
 [#6346](https://github.com/operator-framework/operator-sdk/issues/6346)
 [#6100](https://github.com/operator-framework/operator-sdk/issues/6100)
[!3783](https://github.com/operator-framework/operator-sdk/pull/3783)
[#930](https://github.com/operator-framework/operator-lifecycle-manager/issues/930)

 
- Subprojects I am involved with
operator-sdk
operator-lifecycle-manager

**Comment by varshaprasad96** [comment]
+1
/lgtm

**Comment by jberkhahn** [comment]
+1
/lgtm

**Comment by jberkhahn** [comment]
Sent the invite, so closing this issue. Welcome!
