### ISSUE TITLE
REQUEST: New membership for acornett21

### ISSUE THREAD

**Issue by acornett21** [operator-framework/community#98]
### GitHub Username
@acornett21

### Requirements
- [x] I have reviewed the community membership guidelines (https://github.com/operator-framework/community/blob/master/community-membership.md)
- [x] I have enabled 2FA on my GitHub account (https://github.com/settings/security)
- [x] I have subscribed to the operator-framework e-mail list (https://groups.google.com/forum/#!forum/operator-framework)
- [x] I am actively contributing to 1 or more Operator Framework subprojects
- [x] I have two sponsors that meet the sponsor requirements listed in the community membership guidelines
- [x] I have spoken to my sponsors ahead of this application, and they have agreed to sponsor my application

### Sponsors
- @everettraven 
- @jberkhahn 

### List of contributions to the Operator Framework org
- PRs reviewed / authored
   - operator-framework/operator-sdk#6253
   - operator-framework/operator-sdk#6294
   - operator-framework/operator-sdk#6422
- Issues responded to
- Subprojects I am involved with
   - operators
   - olm

**Comment by everettraven** [comment]
+1

**Comment by varshaprasad96** [comment]
+1
@acornett21 has been contributing to Operator SDK heavily, it would be great to have him as a part of our org.
